apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

# Add sync wave annotation
commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

helmCharts:
  - name: elasticsearch
    repo: https://helm.elastic.co
    version: 8.5.1
    releaseName: elk-elasticsearch
    namespace: logging
    valuesFile: elasticsearch-values.yaml
