replicas: 1
minimumMasterNodes: 1
ingress:
  enabled: true
  hosts:
    - host: es-elk.s9.devopscloud.link # Change the hostname as required
      paths:
        - path: /
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
