esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true

secretMounts:
  - name: elasticsearch-master-certs
    secretName: elasticsearch-master-certs
    path: "/usr/share/elasticsearch/config/certs"

service:
  type: ClusterIP
  ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 9200

persistence:
  enabled: true
  size: 30Gi
  storageClass: "default"

resources:
  limits:
    memory: "4Gi"
    cpu: "2"
  requests:
    memory: "2Gi"
    cpu: "1"
