service:
  type: LoadBalancer
  port: 5601
  loadBalancerIP: ""
  nodePort: ""
  annotations: {}
  labels: {}

resources:
  limits:
    memory: "2Gi"
    cpu: "1"
  requests:
    memory: "1Gi"
    cpu: "500m"

annotations:
  argocd.argoproj.io/sync-wave: "1"
