resources:
  - namespace.yaml

helmCharts:
  - name: elasticsearch
    chart: elastic/elasticsearch
    version: 7.17.0
    releaseName: elk-elasticsearch
    namespace: logging
    valuesFile: elasticsearch-values.yaml

  - name: kibana
    chart: elastic/kibana
    version: 7.17.0
    releaseName: elk-kibana
    namespace: logging
    valuesFile: kibana-values.yaml

  - name: logstash
    chart: elastic/logstash
    version: 7.17.0
    releaseName: elk-logstash
    namespace: logging
    valuesFile: logstash-values.yaml

  - name: filebeat
    chart: elastic/filebeat
    version: 7.17.0
    releaseName: elk-filebeat
    namespace: logging
    valuesFile: filebeat-values.yaml
