apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - namespace.yaml

helmCharts:
  - name: elasticsearch
    repo: https://helm.elastic.co
    version: 8.5.1
    releaseName: elasticsearch
    namespace: logging
    valuesFile: elasticsearch-values.yaml

  - name: kibana
    repo: https://helm.elastic.co
    version: 8.5.1
    releaseName: kibana
    namespace: logging
    valuesFile: kibana-values.yaml

  - name: logstash
    repo: https://helm.elastic.co
    version: 8.5.1
    releaseName: logstash
    namespace: logging
    valuesFile: logstash-values.yaml

  - name: filebeat
    repo: https://helm.elastic.co
    version: 8.5.1
    releaseName: filebeat
    namespace: logging
    valuesFile: filebeat-values.yaml
