apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - namespace.yaml

helmCharts:
  - name: eck-stack
    repo: https://helm.elastic.co
    releaseName: eck-stack-with-logstash
    namespace: monitoring
    version: 0.12.1
    valuesFile: values.yaml
