apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    output {
      elasticsearch {
        hosts => ["https://quickstart-es-http:9200"]
        user => "${ES_USER}"
        password => "${ES_PASSWORD}"
      }
    }
