apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-master-certs
  namespace: logging
spec:
  secretName: elasticsearch-master-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: elasticsearch.logging.svc.cluster.local
  dnsNames:
    - elasticsearch.logging.svc.cluster.local
  duration: 2160h # Optional, set to specify certificate duration
  renewBefore: 360h # Optional, set to specify when to renew
  privateKey:
    algorithm: RSA
    size: 2048
